name: Dndkit Deploy on main push

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3.5.3
      - name: Installing dependendcy
        run: npm i
      - name: Build artifact
        run: npm run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3.5.3

      - name: Download production-ready build files
        uses: actions/download-artifact@v3
        with:
          name: production-files

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          deploy_key: ${{ secrets.PRIVATE_KEY }}
          external_repository: dominus10.github.io
          publish_dir: ./public/dndkit
