name: Dndkit Deploy on main push

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4.2.1
      - name: Installing dependency
        run: npm i
      - name: Build artifact
        run: npm run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4.4.3
        with:
          name: production-files
          path: ./dist

      - name: Upload single file as release
        uses: softprops/action-gh-release@v2
        with:
          files: production-files.zip # Specify the single file to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dispatch:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger to gh-pages
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOK }}
          repository: dominus10/dominus10.github.io
          event-type: trigger-download
          client-payload: '{"repository": "dndkit-example"}'
